# Generated by Django 5.1.9 on 2026-05-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accord_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perfume_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=500)),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, max_length=300, null=True
                    ),
                ),
                ("release_year", models.IntegerField(blank=True, null=True)),
                (
                    "concentration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccordNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_source",
                    models.CharField(
                        help_text="fragrantica | keyword | keyword_pass2 | override | manual",
                        max_length=50,
                    ),
                ),
                (
                    "accord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accord_notes",
                        to="catalog.accord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "accords",
                    models.ManyToManyField(
                        related_name="notes",
                        through="catalog.AccordNote",
                        to="catalog.accord",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="accordnote",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accord_notes",
                to="catalog.note",
            ),
        ),
        migrations.CreateModel(
            name="PerfumeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("base", "Base"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfume_notes",
                        to="catalog.note",
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfume_notes",
                        to="catalog.perfume",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="perfume",
            name="notes",
            field=models.ManyToManyField(
                related_name="perfumes",
                through="catalog.PerfumeNote",
                to="catalog.note",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accordnote",
            unique_together={("note", "accord")},
        ),
        migrations.AddIndex(
            model_name="perfumenote",
            index=models.Index(
                fields=["perfume", "layer"], name="catalog_per_perfume_133953_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="perfumenote",
            unique_together={("perfume", "note", "layer")},
        ),
    ]
