# Generated by Django 5.2.14 on 2026-06-17 06:21

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_note_name_gin_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='release_year',
        ),
        migrations.CreateModel(
            name='NoteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.note')),
            ],
            options={
                'verbose_name_plural': 'Note aliases',
                'ordering': ['alias_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['alias_name'], name='catalog_alias_name_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
