# Generated by Django 5.2.14 on 2026-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_perfume_release_year_notealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='main_accords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
