# Generated by Django 5.1.9 on 2026-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("frequency", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "note frequencies",
            },
        ),
    ]
