# Generated by Django 5.2.14 on 2026-05-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_note_name_gin_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.profilegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], max_length=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes', to='catalog.note')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfileNote', to='catalog.note'),
        ),
        migrations.AddIndex(
            model_name='profilenote',
            index=models.Index(fields=['profile', 'layer'], name='profiles_pr_profile_e42cfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilenote',
            unique_together={('profile', 'note', 'layer')},
        ),
    ]
