# Generated by Django 5.1.9 on 2026-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComparisonLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("top_notes", models.JSONField(default=list)),
                ("middle_notes", models.JSONField(default=list)),
                ("base_notes", models.JSONField(default=list)),
                ("results", models.JSONField(default=list)),
                ("duration_ms", models.IntegerField()),
                ("ip_hash", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
