# Generated by Django 5.2.14 on 2026-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonlog',
            name='brand_filter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
